# Generated by Django 4.2.13 on 2024-07-02 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backgroundAudios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="duration",
            field=models.DurationField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="uploaded_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
