# Generated by Django 4.2.13 on 2024-07-03 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backgroundAudios", "0002_alter_audiofile_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="current_position",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
