# Generated by Django 4.2.13 on 2024-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="reminder_time",
            field=models.IntegerField(default=0),
        ),
    ]
