# Generated by Django 4.2.13 on 2024-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PostsAndComments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reply",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
