# Generated by Django 4.2.13 on 2024-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="name",
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
