# Generated by Django 4.2.13 on 2024-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="groupsPhotoes/"),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
