# Generated by Django 4.2.13 on 2024-06-28 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_groupmaterial_media_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmaterial",
            name="uploaded_Time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
